#!/bin/bash
base=`dirname $0`
base=`realpath $base`

if [[ $# -eq 0 ]]; then
  echo "Usage: `basename $0` [FOLDER AP]..."
  echo
  echo "For each FOLDER/AP pair, finds the corresponding INTERFACE, "
  echo " parses FOLDER/INTERFACE.dat and calculates+displays the CDF"
  exit 1
fi

dir=""
args=()
while true; do
  if [[ $# -eq 0 ]]; then break; fi

  if [[ -z $dir ]]; then
    dir="$1"
  else
    if=`cat "$dir/iwconfig.log" 2>&1 | grep "ESSID:\"$1-wifi\"" | sed 's/^\([^ ]\+\) .*/\1/' | head -n 1`
    if [[ ! -e "$dir/$if.dat" ]]; then
      $base/mp-analyze "$dir" > /dev/null
    fi
    args+=("$dir/$if.dat")
    dir=""
  fi

  shift
done

$base/mp-cdf-raw ${args[@]}

# vim:textwidth=0:
