#!/bin/bash
base=`dirname $0`
base=`realpath $base`

if [[ $# -eq 0 ]]; then
  echo "Usage: $0 [FOLDER INTERFACE]..."
  echo
  echo "For each FOLDER/INTERFACE pair, parses FOLDER/INTERFACE.dat"
  echo " and calculates+displayed the CDF"
  exit 1
fi

runr() {
  if [[ $1 == ${1/-up//} ]]; then
    # down
    if [[ $2 == 'totals' ]]; then
      f=3
    else
      f=17
    fi
  else
    # up
    if [[ $2 == 'totals' ]]; then
      f=2
    else
      f=16
    fi
  fi

  cut -d' ' -f$f "$1/$2.dat" | sort -n | \
    # http://stackoverflow.com/questions/16493669/how-to-read-input-from-the-terminal-using-dev-stdin-and-read-csv
  R -q -e "x <- read.csv(file='stdin', header = F); \
           Fn <- ecdf(x[,1]); \
           t <- data.frame(knots(Fn), Fn(knots(Fn))); \
           t" | \
    grep -v ">" | grep -v "knots" | awk '{ print $2 " " $3 }'
}

s="
# PLOT
set xlabel 'Throughput (Mbps)'
set ylabel 'CDF'
set grid
set xrange [0:30]
set yrange [0:100]
set offset graph 0.02
set key right bottom
set title 'CDF'

set style line 1 lt 1 lc rgb \"red\"
set style line 2 lt 2 lc rgb \"royalblue\"
set style line 3 lt 3 lc rgb \"forest-green\"
set style line 4 lt 4 lc rgb \"dark-magenta\"
set style line 5 lt 5 lc rgb \"gray\"
set style line 6 lt 6 lc rgb \"black\"

plot "
o="1"

# http://www.linuxquestions.org/questions/programming-9/processing-command-args-in-bash-367563/
out=""
i=0
lastnm=""
lastap=""
while true; do
  if [[ $# -eq 1 ]]; then break; fi

  if [ $1 ]; then
    nm=`realpath "${1%/}"`
    ap="$2"

    if [[ $nm == $lastnm && $ap == $lastap ]]; then
      i=`echo $i+1 | bc`
    else
      i=1
    fi

    shift
    shift

    if=`cat "$nm/iwconfig.log" 2>&1 | grep "ESSID:\"$ap-wifi\"" | sed 's/^\([^ ]\+\) .*/\1/' | tail -n +$i | head -n 1`
    if [[ -z $if ]]; then
      if [[ $i -eq 1 ]]; then
        echo "[WW] No interface found for ap $ap"
      else
        echo "[WW] No interface found for ap $ap#$i"
      fi
      continue
    fi

    freq=`cat "$nm/iwconfig.log" | grep "$if" -A1 | grep "Freq" | sed 's/.*Frequency:\([0-9\.]*\) \(GHz\).*/\1\2/'`

    if [[ ! -e "$nm/$if.dat" ]]; then
      $base/mp-analyze "$nm" > /dev/null
    fi

    ran=`cat "$nm/test.txt" | grep "TEST TIME" | sed 's/^.*: [^ ]* \(.*\) [A-Z]* [0-9]*$/\1/'`
    ran=`echo "$ran" | sed 's/ /-/g'`
    freq=`cat "$nm/iwconfig.log" | grep "$if" -A1 | grep "Freq" | sed 's/.*Frequency:\([0-9\.]*\) GHz.*/\1/'`

    if [[ $i -eq 1 ]]; then
      title="`basename "$nm"`/$ap"
    else
      title="`basename "$nm"`/$ap#$i"
    fi

    file="$nm/cdf-$ap-${i}.dat"
    if [[ ! -e $file ]]; then
      runr "$nm" "$if" > "$file"
    fi

    s="$s \\
    '$file' using (8*\$1/1048576):(\$2*100) title '$title' with lines ls ($o),"
    o=`echo "$o+1" | bc`

    lastnm="$nm"
    lastap="$ap"
  else
    break; # no more args
  fi
done

s="${s%,}"

echo "$s" | gnuplot -p - > /dev/null 2>&1
echo "$s"

# vim:textwidth=0:
