#!/bin/bash
base="$(dirname "$0")"
base="$(realpath "$base")"
source "$base/common.sh"

if [[ $# -eq 0 ]]; then
  echo "Usage: $(basename "$0") [FOLDER AP]..."
  echo
  echo "For each FOLDER/AP pair, finds the corresponding INTERFACE, "
  echo " parses FOLDER/INTERFACE.dat and calculates+displays the CDF"
  exit 1
fi

dir=""
args=()
for arg; do
  if [[ -z "$dir" ]]; then
    dir="$arg"
  else
    if=`ap21if "$dir" "$arg"`
    "$base/mp-analyze" "$dir" > /dev/null
    args+=("$dir/$if.dat")
    dir=""
  fi
done

"$base/mp-cdf-raw" "${args[@]}"

# vim:textwidth=0:
