#!/usr/bin/perl
use warnings;
use strict;
use File::Basename;

my $me = dirname $0;
open(my $f, '<', $ARGV[0]);
while (<$f>) {
  foreach my $m (/'~\/(.*?)'/) {
    my $dir = dirname "${ENV{'HOME'}}/$1";
    `"$me/mp-analyze" "$dir"`;
  }
}
