#!/bin/bash
base="$(dirname "$0")"
base="$(realpath "$base")"
source "$base/common.sh"

reg="~/([^']*)'"
cdf="/cdf-.*-(bender|zoidberg|fry)"
while read -r line; do
  [[ $line =~ $reg ]] || continue
  path="${BASH_REMATCH[1]}"
  dir=~/"$(dirname "$path")"
  "$base"/mp-analyze "$dir" > /dev/null
  if [[ $path =~ $cdf ]]; then
    if=$(ap21if "$dir" "${BASH_REMATCH[1]}")
    "$base"/mp-cdf-raw -g "$dir/$if.dat" > /dev/null
  fi
done < "$1"
