#!/bin/bash
base="$(dirname "$0")"
base="$(realpath "$base")"
source "$base/common.sh"

reg="~/([^']*)'"
cdf="/cdf-(bender|zoidberg|fry|mptcp-total)"
cdfs=()
while read -r line; do
  [[ $line =~ $reg ]] || continue
  path="${BASH_REMATCH[1]}"
  dir=~/"$(dirname "$path")"
  "$base"/mp-analyze "$dir" > /dev/null
  if [[ $path =~ $cdf ]]; then
    ap="${BASH_REMATCH[1]}"
    if [[ $path =~ mptcp-total ]]; then
      if="totals"
      cdfs+=("$dir/$if.dat")
    else
      ifs=$(ap2if "$dir" "$ap")
      ifs=($ifs)
      for f in ${ifs[@]}; do
        cdfs+=("$dir/$f.dat")
      done
    fi
    cdfs+=(~/"$path")
  fi
done < "$1"

if [[ ${#cdfs[@]} -gt 0 ]]; then
  "$base"/mp-cdf-raw -g -p "${cdfs[@]}"
fi
