#!/bin/bash
base="$(dirname "$0")"
base="$(realpath "$base")"
source "$base/common.sh"

if [[ $# -eq 0 ]]; then
  echo "Usage: $(basename "$0") UP|DOWN [SET]..."
  echo "For each set, determines which ap has the highest average throughput"
  exit 1
fi

bytes() {
  pd="$(ls -d "$1"/*parallel*-"$updown" | head -n +$2 | tail -n1)"
  ap="$(aps "$pd")"
  if="$(ap21if "$pd" "$ap")"
  ps="$(zcat "$pd/stats.log.gz" | grep -P "^$if(,[^,]*){16}$")"
  pbf=$(echo "$ps" | head -n1 | cut -d, -f$3)
  pbl=$(echo "$ps" | tail -n1 | cut -d, -f$3)
  echo "$pbl-$pbf" | bc
}

updown="$1"
shift

for arg; do
  if [[ $updown == "up" ]]; then
    f=10
  else
    f=2
  fi

  p1=$(bytes "$arg" 1 $f)
  p2=$(bytes "$arg" 2 $f)

  if [[ $p2 -gt $p1 ]]; then
    pd="$(ls -d "$arg"/*parallel*-"$updown" | head -n +2 | tail -n1)"
  else
    pd="$(ls -d "$arg"/*parallel*-"$updown" | head -n +1 | tail -n1)"
  fi

  ap="$(aps "$pd")"

  echo "$1: $ap"
done
