#!/bin/bash
base=`dirname $0`
base=`realpath $base`
source "$base/common.sh"

if [[ $# -eq 0 ]]; then
  echo "Usage: `basename $0` UP|DOWN [SET-FOLDER AP]..."
  echo
  echo -n "For each SET-FOLDER/AP pair, merges single, parallel and mptcp"
  echo -n " readings for the interface connected to AP with that of the"
  echo -n " corresponding tests in the other SET-FOLDERs"
  echo "Outputs data into the files {single,parallel,mptcp}-{up,down}.dat"
  exit 1
fi

updown="$1"
shift

for t in single parallel mptcp; do
  touch $t-$updown.dat
done

while true; do
  if [[ $# -lt 2 ]]; then break; fi

  setdir="$1"
  ap="$2"
  shift
  shift

  suffix=`suffix "$setdir" "$updown" "$ap"`
  if [[ -z "$suffix" ]]; then
    echo -e "\e[31mFailed to find a suffix for $ap-wifi in set '$setdir'\e[0m" > /dev/stderr
    continue
  fi

  for t in single parallel mptcp; do
    if [[ $t == "mptcp" ]]; then
      dir=`ls -d "$setdir"/*@$suffix-$updown 2>/dev/null`
    else
      dir=`ls -d "$setdir"/*$t*-$suffix-$updown 2>/dev/null`
    fi

    if [[ -z $dir ]]; then
      echo -e "\e[31mFailed to find a $t@$suffix directory in set '$setdir'\e[0m" > /dev/stderr
      continue;
    fi

    for d in $dir; do
      if=`ap21if "$d" "$ap"`
      if [[ ! -z $if ]]; then break; fi
    done

    if [[ -z $if ]]; then
      echo -e "\e[31mFailed to find $t directory for $ap-wifi in set '$setdir'\e[0m" > /dev/stderr
      continue;
    fi

    if [[ ! -e "$d/$if.dat" ]]; then
      $base/mp-analyze "$d" > /dev/null
    fi

    echo -e "Merging \e[37m`basename $d`\e[0m from set \e[37m$setdir\e[0m into \e[37m$t.dat\e[0m"
    cat "$d/$if.dat" >> "$t-$updown.dat"
  done
done
