#!/bin/bash
ts=`sudo ip rule | grep -P "lookup \d" | sed 's/^.*lookup //'`
if [[ ! -z "$ts" ]]; then
  echo -e "\e[1m:: Cleaning rule tables\e[0m"
  for t in $ts; do
    echo "==> Purging table $t"
    echo "  -> Purging table routes"
    # > /dev/null because these aren't necessary if the profile has been
    # diconnected (netctl removes it)
    sudo ip route del 128.16.80.0/22 table $t 2>/dev/null
    sudo ip route del table $t 2>/dev/null

    echo "  -> Purging table rule"
    sudo ip rule del table $t
  done

  echo "==> Removing old default routes"
  # > /dev/null because we might not have a previous default
  sudo ip route del default scope global via 128.16.80.1 2> /dev/null

  echo
fi

echo -e "\e[1m:: Discovering wireless interfaces\e[0m"
is=`iwconfig 2>&1 | grep ESSID | grep -v off | sed 's/^\([^ ]\+\) .*/\1/' | sort`
first="yes"
t=1
for i in $is; do
  echo -e "==> Found \e[37m$i\e[0m"

  ip=`ip addr show $i | grep "inet " | sed 's/^[^0-9]*\([0-9\.]\+\).*$/\1/'`

  if [[ -z "$ip" ]]; then
    echo -e "\e[31;5m  -> No IP found for interface\e[0m"
    continue
  fi
  if [[ -z `echo $ip | grep -P "/^128\.16\.8/"` ]]; then
    echo -e "\e[31m  -> Skipping since not in 128.16.80.0/22\e[0m"
    continue
  fi
  echo -e "  -> Has IP: \e[37m$ip\e[0m"

  echo "  -> Setting up rules"
  sudo ip rule add from $ip table $t

  echo "  -> Setting up routes"
  sudo ip route add 128.16.80.0/22 dev $i scope link table $t
  sudo ip route add default via 128.16.80.1 dev $i table $t

  if [[ $first == 'yes' ]]; then
    echo -e "\e[37m  -> Setting as default interface\e[0m"
    sudo ip route add default scope global nexthop via 128.16.80.1 dev $i
  fi

  first="no"
  t=`echo "$t+1" | bc`
done
