#!/bin/bash
echo "Prevent autoconnection"
if=`iwconfig 2>&1 | grep ESSID | grep -v off | sed 's/^\([^ ]\+\) .*/\1/' | sort | head -n1`
sudo systemctl stop "netctl-auto@${if}.service"

echo "Stopping current connection"
sudo netctl stop-all

echo "Enable mptcp coupled congestion control"
sudo modprobe mptcp_coupled
sudo sysctl -w net.ipv4.tcp_congestion_control=coupled

echo "Enable mptcp kernel debug"
sudo sysctl -w net.mptcp.mptcp_debug=1

echo "Stopping daemons"
pkill dropbox
pkill hasmail
