#!/bin/bash
base=`dirname $0`
base=`realpath $base`
source "$base/common.sh"
cmd=""

updown=$(updown ".")
isseq=$(isseq ".")

if [[ $1 == 'cdf' ]]; then
  if [[ $isseq -eq 1 ]]; then
    cmd="$base/mp-cdf"
  else
    cmd="$base/mp-cdf-raw"
  fi
elif [[ ! -z $1 ]]; then
  echo "Unsupported display command given"
  exit 2
else
  echo "Usage: $0 CMND [AP...]"
  exit 0
fi

cmdb="$(basename "$cmd")"
shift

if [[ $isseq -eq 0 ]]; then
  for d in ./*-$updown; do
    if [[ ! -e "$d"/totals.dat ]]; then
      "$base"/mp-analyze "$d"
    fi
  done

  "$cmd" ./*-$updown/w*.dat
  exit
fi

if [[ $# -eq 0 ]]; then
  args="$(cat ./*/iwconfig.log 2>&1 | grep "ESSID:\"" | grep -- "-wifi\"" | sed 's/^.*ESSID:"\([^"]*\)-wifi".*/\1/' | sort | uniq)"
  args=($args)
else
  args=("$@")
fi

for ap in "${args[@]}"; do
  suffix="$(suffix "." "$updown" "$ap")"
  if [[ -z "$suffix" ]]; then
    continue
  fi

  cargs=()
  for dir in *[-@]$suffix-$updown; do
    if [[ $cmdb == "mp-cdf-raw" ]]; then
      ifs="$(ap2if "$dir" "$ap")"
      ifs=($ifs)
      for i in "${ifs[@]}"; do
        cargs+=("$dir/$i.dat")
      done
    else
      cargs+=("$dir")
      cargs+=("$ap")
    fi
  done

  echo "$cmdb ${cargs[@]}"
  "$cmd" "${cargs[@]}"
done

# vim:textwidth=0:
