#!/bin/bash
interval=2s
if [[ ! -z $1 ]]; then
  interval=$1
fi

filter=""
if [[ ! -z $2 ]]; then
  filter=$2
  if [[ -z `echo $2 | grep -P "^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$"` ]]; then
    filter=`ping -c 1 $filter | grep PING | sed 's/^[^(]*(//' | sed 's/).*//'`
  fi
fi

while /bin/true; do
  date +%s.%N
  echo ";"
  iwconfig 2> /dev/null \
    | grep 'ESSID:"' -A5 \
    | grep -E "ESSID|Freq|Rate|Signal" \
    | sed 's/^\([^ ]*\) *IEEE.*/CUT\1/' | sed 's/Mode:Managed  //' \
    | paste -s \
    | sed 's/CUT/\n/g' \
    | perl -pe 's/\s{2,}.*?[:=] ?(.*?)/,\1/g' \
    | tail -n +2
  echo ";"
  grep ":" /proc/net/dev | grep -vE "usb|wan|lo" | perl -pe 's/(: |\s{2,})/,/g' | sed 's/^ *//'
  echo ";"
  grep ":" /proc/net/wireless | sed 's/^ *//' | perl -pe 's/(: |\s+)/,/g'
  echo ";"
  grep "TcpExt:" /proc/net/netstat | grep -v "Syn" | sed 's/^TcpExt: //'
  echo ";"
  if [[ -z $2 ]]; then
    ss -inot | grep -v "State"
  else
    ss -inot | grep -v "State" | grep -A1 $filter | sed '/^--$/d'
  fi
  echo "."
  sleep $interval
done
