#!/bin/bash
W="$(curl --silent amiusingmptcp.com | grep big)"
if [[ $W =~ green ]]; then
  echo "MPTCP enabled"
elif [[ $W =~ red ]]; then
  echo "MPTCP not enabled"
else
  echo "I couldn't tell you even if I wanted to"
fi
